spring.application.name=main_server
server.port=8080

#JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


spring.datasource.url=jdbc:postgresql://localhost:5432/earzuhal_main_server


spring.datasource.username=postgres
# Use environment variable for security
spring.datasource.password=${POSTGRES_DB_PASSWORD:?POSTGRES_DB_PASSWORD is not set}
spring.datasource.driver-class-name=org.postgresql.Driver
